### ISSUE TITLE
Missing ingredients.md

### ISSUE THREAD

**Issue by amuetzel** [rixx/obai#1]
The readme refers to the file ingredients.md. But it is nowhere to be found in the repo. (Btw: Thanks for the workshop!)

**Comment by rixx** [comment]
Thanks, @amuetzel :)

**Comment by amuetzel** [comment]
Thanks for the file! Seems like I didn't just not search enough for the aroma... I'll let you know if I find a nice replacement :-)

**Comment by rixx** [comment]
:+1:
