### ISSUE TITLE
License and usage of the name Obai

### ISSUE THREAD

**Issue by schmittlauch** [rixx/obai#2]
I want to offer a sherbet mix workshop at a Chaos event this year. I see myself mainly as an infrastructure provider for offering the tools and ingredients needed to mix one's own obai sherbet.
Can I use the name Obai?
If the general answer is yes, a clarification about the recipe's license and use of the name _obai_ in the README may be helpful.

**Comment by rixx** [comment]
Good point, thanks, I'll add it!

Sure, call yourself Obai, no worries. Which event are you going to be at, and do you need any help/leftover ingredients/packaging that I might have lying around here?

**Comment by schmittlauch** [comment]
I'll be at Datenspuren 2016 in Dresden. We haven't ordered ingredients yet, so getting some from you may be an option. What do you have lying around? Especially the aroma seems to be a point where we'll have to expriment as the one you used isn't on Amazon anymore.

**Comment by rixx** [comment]
Hm, Aroma and caffeine are actually the only things we probably still have (that and some glasses/bottle-thingies). I hadn't planned to go to Datenspuren, but dropping off some stuff shouldn't be a problem. Anything else you need?

**Comment by schmittlauch** [comment]
Printed labels for the tubes might come handy, if you have some of them left. Otherwise it shouldn't be too expensive to print new ones.
We haven't yet decided how much sherbet we want to be able to mix.

**Comment by rixx** [comment]
The labels we had were for, erm, 30C3 or 31C3. But you can just print them yourself on a normal printer. You can just send me an email (rixx at cutebit.de) for further questions :)
